- clean: [
    '~',
    '~/.mutt'
]

- link:
    ~/.agignore: agignore
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.config/dunst/dunstrc:
        create: true
        path: dunstrc
    ~/.config/gopass/config.yml:
        create: true
        path: gopass.yml
    ~/.config/phpactor/phpactor.yml:
        create: true
        path: phpactor.yml
    ~/.config/rofi/config:
        create: true
        path: rofi.config
    ~/.config/termite/config:
        create: true
        path: termite.config
    ~/.ctags: ctags
    ~/.dircolors: dircolors
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gvimrc: gvimrc
    ~/.i3: i3
    ~/.i3blocks.conf: i3blocks.conf
    ~/.i3status.conf: i3status.conf
    ~/.jshintrc: jshintrc
    ~/.mutt/colorscheme-jess.muttrc:
        create: true
        path: mutt/colorscheme-jess.muttrc
    ~/.mutt/mailcap: mutt/mailcap
    ~/.muttrc: muttrc
    ~/.ncmpcpp/config:
        create: true
        path: ncmpcpp.conf
    ~/.tmux: tmux
    ~/.tmux.conf: tmux.conf
    ~/.tmux_darwin.conf: tmux_darwin.conf
    ~/.tmux_linux.conf: tmux_linux.conf
    ~/.vimperatorrc: vimperatorrc
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.xinitrc: xinitrc
    ~/.Xmodmap: Xmodmap
    ~/.Xresources: Xresources
    ~/.zshrc: zshrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]
    - ["vim +PlugUpdate +PlugClean! +qa", Installing and updating plugins]
